# Generated by Django 4.2.3 on 2025-02-28 14:15

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to=products.models.img_path_categories, verbose_name='Photo du produit'),
            preserve_default=False,
        ),
    ]
